# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
#     - name: running tests
#     for now avoiding tasts
#     - run: npm test
#     deploy the application to netlify
#     - name: Deploy production to Netlify
#       uses: South-Paw/action-netlify-deploy@v1.2.0
#       with:
#         github-token: ${{ secrets.GITHUB_TOKEN }}
#         netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#         netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
#         build-dir: './build'
#         comment-on-commit: true
        
#   deploy to render
    - name: Build and Deploy
      uses: bounceapp/render-action@0.6.0
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        render-token: ${{ secrets.RENDER_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        sleep: 30000
        retries: 20
        wait: 16000
